version: '3.8'

services:
  frontend:
    build:
      context: ./front
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./back
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:doudou123@localhost:5432/dz_beauty
    volumes:
      - ./back:/app  # Mount the back directory for live updates
