name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout Code
        uses: actions/checkout@v2

      # Set up Python environment for FastAPI
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Install FastAPI dependencies
      - name: Install FastAPI dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r backend/requirements.txt

      # Run FastAPI tests
      - name: Run FastAPI Tests
        run: |
          source venv/bin/activate
          pytest backend/tests/

      # Set up Node.js environment for React
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Install React dependencies
      - name: Install React dependencies
        run: |
          cd frontend
          npm install

      # Run React tests
      - name: Run React Tests
        run: |
          cd frontend
          npm test -- --coverage

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'  # Only deploy on changes to the main branch

    steps:
      # Checkout code
      - name: Checkout Code
        uses: actions/checkout@v2

      # Set up Heroku CLI (or other deployment tool)
      - name: Set up Heroku CLI
        uses: akshnz/heroku-cli-action@v1
        with:
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}

      # Deploy to Heroku
      - name: Deploy to Heroku
        run: |
          heroku git:remote -a your-heroku-app-name
          git push heroku main

      # Optionally, run database migrations (if needed)
      - name: Run Database Migrations
        run: |
          source venv/bin/activate
          alembic upgrade head
